[package]
name = "xor_name"
version = "0.0.4"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Type with xor methods"
documentation = "http://maidsafe.net/xor_name/latest"
repository = "https://github.com/maidsafe/xor_name"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://maidsafe.net"

[dependencies]
clippy = {version = "~0.0.37", optional = true}
maidsafe_utilities = "~0.1.5"
rand = "~0.3.12"
rustc-serialize = "~0.3.16"

[dev-dependencies]
cbor = "~0.3.16"
